Add OpenStack (#164)
* add openstack

* add to kustomization

* fix name

* fix

* fix clusterctl tag

* update versions

* use latest cluster template command

* fix name

* fix get kubeconfig

* add separate cleanup command for capi

* standardize names and versions

* fix kustomization

* fix name

* fix name

* fix name

* fix params

* fix params

* fix params

* fix repo name

* fix cleanup task name

* split steps

* clean up

* update default-apps-openstack config

* update kubectl-gs

* delete debug statement

* revert expected nodes change

diff --git a/tekton/tasks/cleanup-capi-pure.yaml b/tekton/tasks/cleanup-capi-pure.yaml
--- a/tekton/tasks/cleanup-capi-pure.yaml
+++ b/tekton/tasks/cleanup-capi-pure.yaml
@@ -1,15 +1,10 @@
 apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
-  name: cleanup
+  name: cleanup-capi-pure
   namespace: test-workloads
-  labels:
-    app.kubernetes.io/name: "standup"
 spec:
   volumes:
-    - name: endpoints-config
-      secret:
-        secretName: standup-endpoints-config
     - name: kubeconfig
       secret:
         secretName: standup-kubeconfig
@@ -18,16 +13,21 @@ spec:
     description: Cluster information is stored here.
   steps:
   - name: cleanup
-    image: quay.io/giantswarm/standup:3.2.0
+    image: quay.io/giantswarm/kubectl-gs:2.4.0
     volumeMounts:
-      - name: endpoints-config
-        mountPath: /etc/endpoints-config
       - name: kubeconfig
         mountPath: /etc/kubeconfig
     script: |
       #! /bin/sh
 
-      export KUBECONFIG=/etc/kubeconfig/$(cat $(workspaces.cluster.path)/installation)
+      set -e
 
-      kubectl -n org-giantswarm delete cluster.cluster.x-k8s.io $(cat $(workspaces.cluster.path)/cluster-id) || true
-      kubectl delete release $(cat $(workspaces.cluster.path)/release-id) || true
+      if [ ! -f $(workspaces.cluster.path)/cluster-id ]; then
+        echo "cluster-id not found, nothing to clean up"
+        exit 0
+      fi
+
+      export KUBECONFIG=/etc/kubeconfig/$(cat $(workspaces.cluster.path)/installation)
+      cluster_id=$(cat $(workspaces.cluster.path)/cluster-id)
+
+      kubectl -n org-multi-project delete app ${cluster_id}-cluster ${cluster_id}-default-apps --ignore-not-found
