Retry apply of cluster CRs

diff --git a/tekton/tasks/create-cluster-capi-hybrid.yaml b/tekton/tasks/create-cluster-capi-hybrid.yaml
--- a/tekton/tasks/create-cluster-capi-hybrid.yaml
+++ b/tekton/tasks/create-cluster-capi-hybrid.yaml
@@ -71,8 +71,30 @@ spec:
         $AZS \
         --output /tmp/nodepool.yaml
 
-      cat /tmp/cluster.yaml | kubectl apply -f -
-      cat /tmp/nodepool.yaml | kubectl apply -f -
+      set +e
+      # Try applying the cluster YAML 5 times to support transient failures in the apply process.
+      for i in $(seq 1 5); do
+        cat /tmp/cluster.yaml | kubectl apply -f -
+        success=$?
+        if [ "$success" -eq "0" ]; then
+          ok="true"
+          break
+        fi
+
+        sleep 15
+      done
+
+      # Try applying the cluster YAML 5 times to support transient failures in the apply process.
+      for i in $(seq 1 5); do
+        cat /tmp/nodepool.yaml | kubectl apply -f -
+        success=$?
+        if [ "$success" -eq "0" ]; then
+          ok="true"
+          break
+        fi
+
+        sleep 15
+      done
 
   - name: legacy-get-kubeconfig
     image: quay.io/giantswarm/kubectl:1.22.3
