Run sonobuoy plugin directly, not using sonobuoy runner.

diff --git a/tekton/tasks/e2e.yaml b/tekton/tasks/e2e.yaml
--- a/tekton/tasks/e2e.yaml
+++ b/tekton/tasks/e2e.yaml
@@ -43,6 +43,12 @@ spec:
         export CP_KUBECONFIG="$(cat $CP_KUBECONFIG_PATH)"
         export TC_KUBECONFIG="$(cat $TC_KUBECONFIG_PATH)"
         /app/run_go_test.sh
+
+        if [ $? -ne 0 ]
+        then
+          echo "e2e tests failed"
+          exit 1
+        fi
       volumeMounts:
         - mountPath: /etc/kubeconfig
           name: kubeconfig
